In [16]:
import pymysql
import pandas as pd

# 생략된 열과 행 모두 표시하기
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [17]:
# 데이터베이스 연결하기
conn = pymysql.connect(host='127.0.0.1', user='apic', password='1234', db='KBODATA', charset='utf8', cursorclass=pymysql.cursors.DictCursor)
# 통로 만들기
cur = conn.cursor()

In [18]:
# 첫 번째 기록창 (2002~)
cur.execute('select * from KBO_TABLE where G >= 0 and year >= 2002;')
result = cur.fetchall()
df1 = pd.DataFrame(result)

# 두 번째 기록창(2002~ , 다음 기록)
cur.execute('select * from KBO_TABLE where BB >= 0 and year >= 2002;')
result = cur.fetchall()
df2 = pd.DataFrame(result)

# 세 번째 기록창(2002~ , 세부기록)
cur.execute('select * from KBO_TABLE where XBH >= 0 and year >= 2002;')
result = cur.fetchall()
df3 = pd.DataFrame(result)

display(df2.head())
display(df3.head())

,id,year,player_name,team_name,AVG,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,HBP,SO,GDP,E,TB,SAC,SF,IBB,SLG,OBP,OPS,MH,RISP,PH_BA,XBH,GO,AO,GO_AO,GW_RBI,BB_K,P_PA,ISOP,XR,GPA
0,11235,2002,김재현,LG,0.334,None,None,None,None,None,None,None,None,None,None,None,54,18,51,6,None,None,None,None,5,0.544,0.462,1.006,26,0.319,0.4,None,None,None,None,None,None,None,None,None,None
1,11236,2002,김상현,LG,0.313,None,None,None,None,None,None,None,None,None,None,None,7,3,18,0,None,None,None,None,1,0.469,0.476,0.945,2,0.333,0.4,None,None,None,None,None,None,None,None,None,None
2,11237,2002,류지현,LG,0.310,None,None,None,None,None,None,None,None,None,None,None,38,2,51,3,None,None,None,None,0,0.380,0.381,0.761,30,0.266,0.0,None,None,None,None,None,None,None,None,None,None
3,11238,2002,이병규,LG,0.293,None,None,None,None,None,None,None,None,None,None,None,50,2,57,6,None,None,None,None,12,0.450,0.375,0.825,30,0.253,0.0,None,None,None,None,None,None,None,None,None,None
4,11239,2002,박용택,LG,0.288,None,None,None,None,None,None,None,None,None,None,None,38,6,109,11,None,None,None,None,1,0.467,0.359,0.826,31,0.317,0.5,None,None,None,None,None,None,None,None,None,None

,id,year,player_name,team_name,AVG,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,HBP,SO,GDP,E,TB,SAC,SF,IBB,SLG,OBP,OPS,MH,RISP,PH_BA,XBH,GO,AO,GO_AO,GW_RBI,BB_K,P_PA,ISOP,XR,GPA
0,18365,2002,김재현,LG,0.334,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,30,88,60,1.47,0,1.06,4.18,0.209,73.1,0.344
1,18366,2002,김상현,LG,0.313,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2,3,1,3.00,0,0.39,4.33,0.156,7.7,0.331
2,18367,2002,류지현,LG,0.310,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,18,91,87,1.05,0,0.75,3.99,0.071,51.0,0.266
3,18368,2002,이병규,LG,0.293,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,37,135,85,1.59,0,0.88,3.72,0.157,63.4,0.281
4,18369,2002,박용택,LG,0.288,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,43,95,67,1.42,0,0.35,4.05,0.179,61.3,0.278

In [19]:
# Null값 모두 제거

df1.dropna(inplace=True, axis=1)
df2.dropna(inplace=True, axis=1)
df3.dropna(inplace=True, axis=1)

df2.drop(columns=['id'], inplace=True)
df3.drop(columns=['id'], inplace=True)

display(df1.head())
display(df2.head())
display(df3.head())

,id,year,player_name,team_name,AVG,G,PA,AB,R,H,2B,3B,HR,RBI,TB,SAC,SF
0,3916,2002,최형우,삼성,0.400,4,6,5,0,2,2,0,0,0,4,1,0
1,3917,2002,마해영,삼성,0.323,133,596,532,92,172,40,2,33,116,315,0,6
2,3918,2002,이승엽,삼성,0.323,133,617,511,123,165,42,2,47,126,352,0,2
3,3919,2002,김한수,삼성,0.311,127,541,486,69,151,23,1,17,76,227,2,4
4,3920,2002,강동우,삼성,0.288,130,521,466,75,134,23,3,9,49,190,7,1

,year,player_name,team_name,AVG,BB,HBP,SO,GDP,IBB,SLG,OBP,OPS,MH,RISP,PH_BA
0,2002,김재현,LG,0.334,54,18,51,6,5,0.544,0.462,1.006,26,0.319,0.4
1,2002,김상현,LG,0.313,7,3,18,0,1,0.469,0.476,0.945,2,0.333,0.4
2,2002,류지현,LG,0.310,38,2,51,3,0,0.380,0.381,0.761,30,0.266,0.0
3,2002,이병규,LG,0.293,50,2,57,6,12,0.450,0.375,0.825,30,0.253,0.0
4,2002,박용택,LG,0.288,38,6,109,11,1,0.467,0.359,0.826,31,0.317,0.5

,year,player_name,team_name,AVG,XBH,GO,AO,GO_AO,GW_RBI,BB_K,P_PA,ISOP,XR,GPA
0,2002,김재현,LG,0.334,30,88,60,1.47,0,1.06,4.18,0.209,73.1,0.344
1,2002,김상현,LG,0.313,2,3,1,3.00,0,0.39,4.33,0.156,7.7,0.331
2,2002,류지현,LG,0.310,18,91,87,1.05,0,0.75,3.99,0.071,51.0,0.266
3,2002,이병규,LG,0.293,37,135,85,1.59,0,0.88,3.72,0.157,63.4,0.281
4,2002,박용택,LG,0.288,43,95,67,1.42,0,0.35,4.05,0.179,61.3,0.278

In [20]:
# 세 기록 합치기

df_merged = df1.merge(df2, on=['year', 'player_name', 'team_name', 'AVG'], how='outer') \
                .merge(df3, on=['year', 'player_name', 'team_name', 'AVG'], how='outer')

# df_merged.drop(columns=['id_x', 'id_y', 'year_x', 'year_y', 'player_name_x', 'player_name_y', 'team_name_x', 'team_name_y', 'AVG_x', 'AVG_y'])
df_merged.head()

,id,year,player_name,team_name,AVG,G,PA,AB,R,H,2B,3B,HR,RBI,TB,SAC,SF,BB,HBP,SO,GDP,IBB,SLG,OBP,OPS,MH,RISP,PH_BA,XBH,GO,AO,GO_AO,GW_RBI,BB_K,P_PA,ISOP,XR,GPA
0,4110,2002,가르시아,한화,0.260,24,77,73,7,19,3,1,2,8,30,0,0,4.0,0.0,20.0,1.0,0.0,0.411,0.299,0.710,5.0,0.375,0.000,6.0,19.0,15.0,1.27,0.0,0.20,3.62,0.151,8.5,0.237
1,4025,2002,강귀태,현대,0.272,74,155,147,17,40,8,0,1,16,51,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3920,2002,강동우,삼성,0.288,130,521,466,75,134,23,3,9,49,190,7,1,46.0,1.0,76.0,9.0,0.0,0.408,0.352,0.760,36.0,0.330,0.000,35.0,150.0,107.0,1.40,0.0,0.61,3.97,0.120,65.0,0.260
3,4031,2002,강병식,현대,0.208,89,147,130,16,27,3,1,6,20,50,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4055,2002,강봉규,두산,0.250,93,182,160,30,40,6,1,5,25,63,3,1,16.0,2.0,43.0,4.0,1.0,0.394,0.324,0.718,9.0,0.350,0.281,12.0,36.0,42.0,0.86,0.0,0.37,4.21,0.144,21.2,0.244

In [22]:
cur.execute('select * from KBO_TABLE where year = 2002 and player_name = "강귀태";')
result = cur.fetchall()
pd.DataFrame(result)

,id,year,player_name,team_name,AVG,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,HBP,SO,GDP,E,TB,SAC,SF,IBB,SLG,OBP,OPS,MH,RISP,PH_BA,XBH,GO,AO,GO_AO,GW_RBI,BB_K,P_PA,ISOP,XR,GPA
0,4025,2002,강귀태,현대,0.272,74,155,147,17,40,8,0,1,16,None,None,None,None,None,None,None,51,3,1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [15]:
conn.close()