In [1]:
import pymysql
import pandas as pd

# 생략된 열과 행 모두 표시하기
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [2]:
# 데이터베이스 연결하기
conn = pymysql.connect(host='127.0.0.1', user='apic', password='1234', db='KBODATA', charset='utf8', cursorclass=pymysql.cursors.DictCursor)
# 통로 만들기
cur = conn.cursor()

In [3]:
cur.execute('select * from KBO_TABLE where XBH >= 0 and year >= 2002;')
result = cur.fetchall()
df1 = pd.DataFrame(result)

df1.head()

,id,year,player_name,team_name,AVG,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,HBP,SO,GDP,E,TB,SAC,SF,IBB,SLG,OBP,OPS,MH,RISP,PH_BA,XBH,GO,AO,GO_AO,GW_RBI,BB_K,P_PA,ISOP,XR,GPA
0,29168,2002,최형우,삼성,0.400,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2,2,1,2.00,0,0.00,2.83,0.400,1.2,0.380
1,29169,2002,마해영,삼성,0.323,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,75,142,150,0.95,0,0.62,3.54,0.269,110.6,0.322
2,29170,2002,이승엽,삼성,0.323,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,91,103,136,0.76,0,0.82,4.13,0.366,136.1,0.368
3,29171,2002,김한수,삼성,0.311,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,41,153,125,1.22,0,0.57,3.69,0.156,79.0,0.284
4,29172,2002,강동우,삼성,0.288,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,35,150,107,1.40,0,0.61,3.97,0.120,65.0,0.260

In [4]:
# 첫 번째 기록창 (2002~)
cur.execute('select * from KBO_TABLE where G >= 0 and year >= 2002;')
result = cur.fetchall()
df1 = pd.DataFrame(result)

# 두 번째 기록창(2002~ , 다음 기록)
cur.execute('select * from KBO_TABLE where BB >= 0 and year >= 2002;')
result = cur.fetchall()
df2 = pd.DataFrame(result)

# 세 번째 기록창(2002~ , 세부기록)
cur.execute('select * from KBO_TABLE where XBH >= 0 and year >= 2002;')
result = cur.fetchall()
df3 = pd.DataFrame(result)

# display(df1.head())
# display(df2.head())
display(df3.head())

,id,year,player_name,team_name,AVG,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,HBP,SO,GDP,E,TB,SAC,SF,IBB,SLG,OBP,OPS,MH,RISP,PH_BA,XBH,GO,AO,GO_AO,GW_RBI,BB_K,P_PA,ISOP,XR,GPA
0,29168,2002,최형우,삼성,0.400,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2,2,1,2.00,0,0.00,2.83,0.400,1.2,0.380
1,29169,2002,마해영,삼성,0.323,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,75,142,150,0.95,0,0.62,3.54,0.269,110.6,0.322
2,29170,2002,이승엽,삼성,0.323,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,91,103,136,0.76,0,0.82,4.13,0.366,136.1,0.368
3,29171,2002,김한수,삼성,0.311,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,41,153,125,1.22,0,0.57,3.69,0.156,79.0,0.284
4,29172,2002,강동우,삼성,0.288,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,35,150,107,1.40,0,0.61,3.97,0.120,65.0,0.260

In [5]:
# Null값 모두 제거

df1.dropna(inplace=True, axis=1)
df2.dropna(inplace=True, axis=1)
df3.dropna(inplace=True, axis=1)

df2.drop(columns=['id'], inplace=True)
df3.drop(columns=['id'], inplace=True)

display(df1.head())
print()
# display(df2.head())
# print()
display(df3.head())

,id,year,player_name,team_name,AVG,G,PA,AB,R,H,2B,3B,HR,RBI,TB,SAC,SF
0,3923,2002,최형우,삼성,0.400,4,6,5,0,2,2,0,0,0,4,1,0
1,3924,2002,마해영,삼성,0.323,133,596,532,92,172,40,2,33,116,315,0,6
2,3925,2002,이승엽,삼성,0.323,133,617,511,123,165,42,2,47,126,352,0,2
3,3926,2002,김한수,삼성,0.311,127,541,486,69,151,23,1,17,76,227,2,4
4,3927,2002,강동우,삼성,0.288,130,521,466,75,134,23,3,9,49,190,7,1

,year,player_name,team_name,AVG,XBH,GO,AO,GO_AO,GW_RBI,BB_K,P_PA,ISOP,XR,GPA
0,2002,최형우,삼성,0.400,2,2,1,2.00,0,0.00,2.83,0.400,1.2,0.380
1,2002,마해영,삼성,0.323,75,142,150,0.95,0,0.62,3.54,0.269,110.6,0.322
2,2002,이승엽,삼성,0.323,91,103,136,0.76,0,0.82,4.13,0.366,136.1,0.368
3,2002,김한수,삼성,0.311,41,153,125,1.22,0,0.57,3.69,0.156,79.0,0.284
4,2002,강동우,삼성,0.288,35,150,107,1.40,0,0.61,3.97,0.120,65.0,0.260

In [ ]:
# 세 기록 합치기

df_merged = df1.merge(df2, on=['year', 'player_name', 'team_name', 'AVG'], how='outer') \
                .merge(df3, on=['year', 'player_name', 'team_name', 'AVG'], how='outer')

,id,year,player_name,team_name,AVG,G,PA,AB,R,H,2B,3B,HR,RBI,TB,SAC,SF,BB,HBP,SO,GDP,IBB,SLG,OBP,OPS,MH,RISP,PH_BA,XBH,GO,AO,GO_AO,GW_RBI,BB_K,P_PA,ISOP,XR,GPA
0,4117,2002,가르시아,한화,0.260,24,77,73,7,19,3,1,2,8,30,0,0,4.0,0.0,20.0,1.0,0.0,0.411,0.299,0.710,5.0,0.375,0.000,6.0,19.0,15.0,1.27,0.0,0.2,3.62,0.151,8.5,0.237
1,4117,2002,가르시아,한화,0.260,24,77,73,7,19,3,1,2,8,30,0,0,4.0,0.0,20.0,1.0,0.0,0.411,0.299,0.710,5.0,0.375,0.000,6.0,19.0,15.0,1.27,0.0,0.2,3.62,0.151,8.5,0.237
2,21972,2002,가르시아,한화,0.260,24,77,73,7,19,3,1,2,8,30,0,0,4.0,0.0,20.0,1.0,0.0,0.411,0.299,0.710,5.0,0.375,0.000,6.0,19.0,15.0,1.27,0.0,0.2,3.62,0.151,8.5,0.237
3,21972,2002,가르시아,한화,0.260,24,77,73,7,19,3,1,2,8,30,0,0,4.0,0.0,20.0,1.0,0.0,0.411,0.299,0.710,5.0,0.375,0.000,6.0,19.0,15.0,1.27,0.0,0.2,3.62,0.151,8.5,0.237
4,4032,2002,강귀태,현대,0.272,74,155,147,17,40,8,0,1,16,51,3,1,2.0,2.0,20.0,3.0,0.0,0.347,0.289,0.636,7.0,0.279,0.182,9.0,42.0,46.0,0.91,0.0,0.1,3.25,0.075,13.0,0.217

In [18]:
df_merged[df_merged['year'] == 2024]

          id  year player_name team_name    AVG    G   PA   AB    R    H  2B  \
14413  11028  2024          강건        KT  0.000    1    0    0    0    0   0
14414  28906  2024          강건        KT  0.000    1    0    0    0    0   0
14415  11029  2024         강민성        KT  0.000    1    1    1    0    0   0
14416  28907  2024         강민성        KT  0.000    1    1    1    0    0   0
14417  10871  2024         강민호        삼성  0.303  136  452  403   48  122  19
14418  28749  2024         강민호        삼성  0.303  136  452  403   48  122  19
14419  11006  2024         강백호        KT  0.289  144  614  550   92  159  27
14420  28884  2024         강백호        KT  0.289  144  614  550   92  159  27
14421  11074  2024         강성우        롯데  0.500    2    3    2    0    1   0
14422  28952  2024         강성우        롯데  0.500    2    3    2    0    1   0
14423  11102  2024         강승구        롯데  0.000    5    2    2    0    0   0
14424  28980  2024         강승구        롯데  0.000    5    2    2    0    0   0
14425  10961  2024         강승호        두산  0.280  140  566  521   81  146  34
14426  28839  2024         강승호        두산  0.280  140  566  521   81  146  34
14427  11058  2024         강진성       SSG  0.185   16   31   27    4    5   0
14428  28936  2024         강진성       SSG  0.185   16   31   27    4    5   0
14429  11103  2024         강태율        롯데  0.000   10   10   10    0    0   0
14430  28981  2024         강태율        롯데  0.000   10   10   10    0    0   0
14431  10895  2024         강한울        삼성  0.095   18   25   21    1    2   0
14432  28773  2024         강한울        삼성  0.095   18   25   21    1    2   0
14433  11002  2024         강현우        KT  0.308   18   36   26    4    8   1
14434  28880  2024         강현우        KT  0.308   18   36   26    4    8   1
14435  11049  2024         고명준       SSG  0.250  106  366  340   33   85  13
14436  28927  2024         고명준       SSG  0.250  106  366  340   33   85  13
14437  11081  2024         고승민        롯데  0.308  120  532  481   79  148  27
14438  28959  2024         고승민        롯데  0.308  120  532  481   79  148  27
14439  11181  2024         고영우        키움  0.256   94  290  254   21   65  12
14440  29059  2024         고영우        키움  0.256   94  290  254   21   65  12
14441  10854  2024         고종욱       KIA  0.250   28   36   32    3    8   2
14442  28732  2024         고종욱       KIA  0.250   28   36   32    3    8   2
14443  10896  2024         공민규        삼성  0.071   12   17   14    1    1   0
14444  28774  2024         공민규        삼성  0.071   12   17   14    1    1   0
14445  10859  2024         곽도규       KIA  0.000    1    0    0    0    0   0
14446  28737  2024         곽도규       KIA  0.000    1    0    0    0    0   0
14447  10921  2024         구본혁        LG  0.257  133  389  339   48   87  14
14448  28799  2024         구본혁        LG  0.257  133  389  339   48   87  14
14449  10868  2024         구자욱        삼성  0.343  129  568  493   92  169  39
14450  28746  2024         구자욱        삼성  0.343  129  568  493   92  169  39
14451  11122  2024         권광민        한화  0.271   19   51   48   10   13   3
14452  29000  2024         권광민        한화  0.271   19   51   48   10   13   3
14453  11019  2024         권동진        KT  0.222    9   10    9    3    2   0
14454  28897  2024         권동진        KT  0.222    9   10    9    3    2   0
14455  10979  2024          권휘        두산  0.000    1    1    1    0    0   0
14456  28857  2024          권휘        두산  0.000    1    1    1    0    0   0
14457  11147  2024         권희동        NC  0.300  123  511  416   66  125  22
14458  29025  2024         권희동        NC  0.300  123  511  416   66  125  22
14459  10980  2024         김강률        두산  0.000    1    0    0    0    0   0
14460  10980  2024         김강률        두산  0.000    1    0    0    0    0   0
14461  28858  2024         김강률        두산  0.000    1    0    0    0    0   0
14462  28858  2024         김강률        두산  0.000    1    0    0    0    0   0
14463  11129  2024         김강민        한화  0.224   41   87   76    5   17   0
14464  29007  2024         김강민        한화  0.224   41   87   76    5   17   0
14465  11104  2024         김강현        롯데  0.000    2    0    0    0    0   0
14466  28982  2024         김강현        롯데  0.000    2    0    0    0    0   0
14467  11026  2024         김건형        KT  0.125   13   25   24    2    3   1
14468  28904  2024         김건형        KT  0.125   13   25   24    2    3   1
14469  11180  2024         김건희        키움  0.257   83  283  261   27   67  15
14470  29058  2024         김건희        키움  0.257   83  283  261   27   67  15
14471  10855  2024         김규성       KIA  0.250   27   15   12    5    3   1
14472  28733  2024         김규성       KIA  0.250   27   15   12    5    3   1
14473  10962  2024         김기연        두산  0.278   95  283  252   31   70  10
14474  28840  2024         김기연        두산  0.278   95  283  252   31   70  10
14475  10898  2024         김대우        삼성  0.000    1    0    0    0    0   0
14476  28776  2024         김대우        삼성  0.000    1    0    0    0    0   0
14477  10909  2024         김대원        LG  0.500   19    4    4    5    2   0
14478  28787  2024         김대원        LG  0.500   19    4    4    5    2   0
14479  10976  2024         김대한        두산  0.133   61   89   75   10   10   1
14480  28854  2024         김대한        두산  0.133   61   89   75   10   10   1
14481  10933  2024         김대현        LG  0.000    3    0    0    0    0   0
14482  28811  2024         김대현        LG  0.000    3    0    0    0    0   0
14483  10835  2024         김도영       KIA  0.347  141  625  544  143  189  29
14484  28713  2024         김도영       KIA  0.347  141  625  544  143  189  29
14485  10899  2024         김도환        삼성  0.000    1    3    3    0    0   0
14486  28777  2024         김도환        삼성  0.000    1    3    3    0    0   0
14487  10893  2024         김동엽        삼성  0.111    8   21   18    1    2   1
14488  28771  2024         김동엽        삼성  0.111    8   21   18    1    2   1
14489  11202  2024         김동욱        키움  0.000    1    0    0    0    0   0
14490  29080  2024         김동욱        키움  0.000    1    0    0    0    0   0
14491  10981  2024         김동주        두산  0.000    1    0    0    0    0   0
14492  10981  2024         김동주        두산  0.000    1    0    0    0    0   0
14493  28859  2024         김동주        두산  0.000    1    0    0    0    0   0
14494  28859  2024         김동주        두산  0.000    1    0    0    0    0   0
14495  10894  2024         김동진        삼성  0.108   30   42   37    5    4   0
14496  28772  2024         김동진        삼성  0.108   30   42   37    5    4   0
14497  11191  2024         김동헌        키움  0.200    2    7    5    0    1   0
14498  29069  2024         김동헌        키움  0.200    2    7    5    0    1   0
14499  11093  2024         김동혁        롯데  0.200   39   17   15    8    3   0
14500  28971  2024         김동혁        롯데  0.200   39   17   15    8    3   0
14501  10834  2024         김두현       KIA  0.400    3    6    5    2    2   0
14502  28712  2024         김두현       KIA  0.400    3    6    5    2    2   0
14503  10982  2024         김명신        두산  0.000    3    0    0    0    0   0
14504  10982  2024         김명신        두산  0.000    3    0    0    0    0   0
14505  28860  2024         김명신        두산  0.000    3    0    0    0    0   0
14506  28860  2024         김명신        두산  0.000    3    0    0    0    0   0
14507  11030  2024          김민        KT  0.000    1    0    0    0    0   0
14508  28908  2024          김민        KT  0.000    1    0    0    0    0   0
14509  10983  2024         김민규        두산  0.000    1    0    0    0    0   0
14510  10983  2024         김민규        두산  0.000    1    0    0    0    0   0
14511  28861  2024         김민규        두산  0.000    1    0    0    0    0   0
14512  28861  2024         김민규        두산  0.000    1    0    0    0    0   0
14513  11092  2024         김민석        롯데  0.211   41   83   76   14   16   3
14514  28970  2024         김민석        롯데  0.211   41   83   76   14   16   3
14515  11094  2024         김민성        롯데  0.200   35   84   70    6   14   5
14516  28972  2024         김민성        롯데  0.200   35   84   70    6   14   5
14517  10928  2024         김민수        LG  0.150   19   22   20    1    3   0
14518  28806  2024         김민수        LG  0.150   19   22   20    1    3   0
14519  10879  2024         김민수        삼성  0.250    9    8    8    1    2   0
14520  28757  2024         김민수        삼성  0.250    9    8    8    1    2   0
14521  11057  2024         김민식       SSG  0.208   45  126  106   10   22   5
14522  28935  2024         김민식       SSG  0.208   45  126  106   10   22   5
14523  10860  2024         김민주       KIA  0.000    1    0    0    0    0   0
14524  28738  2024         김민주       KIA  0.000    1    0    0    0    0   0
14525  11000  2024         김민혁        KT  0.353  115  393  351   47  124  14
14526  28878  2024         김민혁        KT  0.353  115  393  351   47  124  14
14527  10971  2024         김민혁        두산  0.200    5    8    5    1    1   0
14528  28849  2024         김민혁        두산  0.200    5    8    5    1    1   0
14529  10923  2024         김범석        LG  0.241   70  180  162   14   39   4
14530  28801  2024         김범석        LG  0.241   70  180  162   14   39   4
14531  11166  2024         김범준        NC  0.000    5    5    5    0    0   0
14532  29044  2024         김범준        NC  0.000    5    5    5    0    0   0
14533  10999  2024         김병준        KT  0.357   35   16   14    9    5   0
14534  28877  2024         김병준        KT  0.357   35   16   14    9    5   0
14535  11194  2024         김병휘        키움  0.169   28   71   59    6   10   3
14536  29072  2024         김병휘        키움  0.169   28   71   59    6   10   3
14537  10861  2024         김사윤       KIA  0.000    1    0    0    0    0   0
14538  28739  2024         김사윤       KIA  0.000    1    0    0    0    0   0
14539  11008  2024         김상수        KT  0.276  113  420  369   60  102  18
14540  28886  2024         김상수        KT  0.276  113  420  369   60  102  18
14541  11105  2024         김상수        롯데  0.000    1    0    0    0    0   0
14542  28983  2024         김상수        롯데  0.000    1    0    0    0    0   0
14543  11135  2024         김서현        한화  0.000    1    0    0    0    0   0
14544  29013  2024         김서현        한화  0.000    1    0    0    0    0   0
14545  11203  2024         김선기        키움  0.000    1    0    0    0    0   0
14546  29081  2024         김선기        키움  0.000    1    0    0    0    0   0
14547  10836  2024         김선빈       KIA  0.329  116  466  423   48  139  23
14548  28714  2024         김선빈       KIA  0.329  116  466  423   48  139  23
14549  10934  2024         김성우        LG  0.000    4    5    5    0    0   0
14550  28812  2024         김성우        LG  0.000    4    5    5    0    0   0
14551  11161  2024         김성욱        NC  0.204  129  412  358   55   73   8
14552  29039  2024         김성욱        NC  0.204  129  412  358   55   73   8
14553  10881  2024         김성윤        삼성  0.243   32   89   74   15   18   4
14554  28759  2024         김성윤        삼성  0.243   32   89   74   15   18   4
14555  10919  2024         김성진        LG  0.267   14   16   15    1    4   0
14556  28797  2024         김성진        LG  0.267   14   16   15    1    4   0
14557  11055  2024         김성현       SSG  0.227   71  167  141   21   32   3
14558  28933  2024         김성현       SSG  0.227   71  167  141   21   32   3
14559  11167  2024         김세훈        NC  0.000    7    5    4    0    0   0
14560  29045  2024         김세훈        NC  0.000    7    5    4    0    0   0
14561  11158  2024         김수윤        NC  0.222    9   10    9    0    2   0
14562  29036  2024         김수윤        NC  0.222    9   10    9    0    2   0
14563  10935  2024         김수인        LG  0.000    4    3    3    0    0   0
14564  28813  2024         김수인        LG  0.000    4    3    3    0    0   0
14565  11204  2024         김수환        키움  0.000    2    3    3    0    0   0
14566  29082  2024         김수환        키움  0.000    2    3    3    0    0   0
14567  10862  2024         김승현       KIA  0.000    1    0    0    0    0   0
14568  28740  2024         김승현       KIA  0.000    1    0    0    0    0   0
14569  11197  2024         김시앙        키움  0.143    6    7    7    1    1   0
14570  29075  2024         김시앙        키움  0.143    6    7    7    1    1   0
14571  11205  2024         김연주        키움  0.000    4    0    0    0    0   0
14572  29083  2024         김연주        키움  0.000    4    0    0    0    0   0
14573  11168  2024         김영규        NC  0.000    1    0    0    0    0   0
14574  29046  2024         김영규        NC  0.000    1    0    0    0    0   0
14575  10878  2024         김영웅        삼성  0.252  126  509  456   65  115  16
14576  28756  2024         김영웅        삼성  0.252  126  509  456   65  115  16
14577  10936  2024         김영준        LG  0.000    1    0    0    0    0   0
14578  28814  2024         김영준        LG  0.000    1    0    0    0    0   0
14579  11031  2024         김영현        KT  0.000    1    0    0    0    0   0
14580  28909  2024         김영현        KT  0.000    1    0    0    0    0   0
14581  11198  2024         김웅빈        키움  0.125   12   38   32    2    4   0
14582  29076  2024         김웅빈        키움  0.125   12   38   32    2    4   0
14583  11106  2024         김원중        롯데  0.000    1    0    0    0    0   0
14584  28984  2024         김원중        롯데  0.000    1    0    0    0    0   0
14585  10937  2024         김유영        LG  0.000    2    0    0    0    0   0
14586  28815  2024         김유영        LG  0.000    2    0    0    0    0   0
14587  11206  2024         김윤하        키움  0.000    1    0    0    0    0   0
14588  29084  2024         김윤하        키움  0.000    1    0    0    0    0   0
14589  10975  2024         김인태        두산  0.174   10   26   23    3    4   0
14590  28853  2024         김인태        두산  0.174   10   26   23    3    4   0
14591  11127  2024         김인환        한화  0.237   51  143  131   11   31   2
14592  29005  2024         김인환        한화  0.237   51  143  131   11   31   2
14593  10883  2024         김재상        삼성  0.238   35   91   84   13   20   4
14594  28761  2024         김재상        삼성  0.238   35   91   84   13   20   4
14595  10888  2024         김재성        삼성  0.200   10   23   20    3    4   1
14596  28766  2024         김재성        삼성  0.200   10   23   20    3    4   1
14597  11169  2024         김재열        NC  0.000    1    0    0    0    0   0
14598  29047  2024         김재열        NC  0.000    1    0    0    0    0   0
14599  11207  2024         김재웅        키움  0.000    2    0    0    0    0   0
14600  29085  2024         김재웅        키움  0.000    2    0    0    0    0   0
14601  10900  2024         김재윤        삼성  0.000    3    0    0    0    0   0
14602  28778  2024         김재윤        삼성  0.000    3    0    0    0    0   0
14603  10891  2024         김재혁        삼성  0.184   35   54   49    6    9   2
14604  28769  2024         김재혁        삼성  0.184   35   54   49    6    9   2
14605  11185  2024         김재현        키움  0.243  110  326  288   27   70  11
14606  29063  2024         김재현        키움  0.243  110  326  288   27   70  11
14607  10957  2024         김재호        두산  0.302   57  154  126   20   38   5
14608  28835  2024         김재호        두산  0.302   57  154  126   20   38   5
14609  10960  2024         김재환        두산  0.283  136  552  474   78  134  28
14610  28838  2024         김재환        두산  0.283  136  552  474   78  134  28
14611  10927  2024         김주성        LG  0.167   12    9    6    1    1   0
14612  28805  2024         김주성        LG  0.167   12    9    6    1    1   0
14613  11155  2024         김주원        NC  0.252  134  475  385   61   97  18
14614  29033  2024         김주원        NC  0.252  134  475  385   61   97  18
14615  11196  2024         김주형        키움  0.150   22   25   20    0    3   0
14616  29074  2024         김주형        키움  0.150   22   25   20    0    3   0
14617  11017  2024         김준태        KT  0.240   23   30   25    6    6   2
14618  28895  2024         김준태        KT  0.240   23   30   25    6    6   2
14619  10870  2024         김지찬        삼성  0.316  135  535  453  102  143  16
14620  28748  2024         김지찬        삼성  0.316  135  535  453  102  143  16
14621  10938  2024         김진성        LG  0.000    4    0    0    0    0   0
14622  28816  2024         김진성        LG  0.000    4    0    0    0    0   0
14623  11063  2024         김찬형       SSG  0.000    5    9    9    0    0   0
14624  28941  2024         김찬형       SSG  0.000    5    9    9    0    0   0
14625  11064  2024         김창평       SSG  0.000    6    9    7    1    0   0
14626  28942  2024         김창평       SSG  0.000    6    9    7    1    0   0
14627  10852  2024         김태군       KIA  0.264  105  270  235   24   62   7
14628  28730  2024         김태군       KIA  0.264  105  270  235   24   62   7
14629  10978  2024         김태근        두산  0.087   43   27   23    7    2   0
14630  28856  2024         김태근        두산  0.087   43   27   23    7    2   0
14631  11115  2024         김태연        한화  0.291  126  472  413   59  120  24
14632  28993  2024         김태연        한화  0.291  126  472  413   59  120  24
14633  11187  2024         김태진        키움  0.222   81  202  189   26   42   6
14634  29065  2024         김태진        키움  0.222   81  202  189   26   42   6
14635  10901  2024         김태훈        삼성  0.000    1    0    0    0    0   0
14636  28779  2024         김태훈        삼성  0.000    1    0    0    0    0   0
14637  10889  2024         김태훈        삼성  0.200   12   21   20    2    4   1
14638  28767  2024         김태훈        삼성  0.200   12   21   20    2    4   1
14639  10984  2024         김택연        두산  0.000    1    0    0    0    0   0
14640  10984  2024         김택연        두산  0.000    1    0    0    0    0   0
14641  28862  2024         김택연        두산  0.000    1    0    0    0    0   0
14642  28862  2024         김택연        두산  0.000    1    0    0    0    0   0
14643  11145  2024         김한별        NC  0.318   40   50   44    8   14   1
14644  29023  2024         김한별        NC  0.318   40   50   44    8   14   1
14645  10872  2024         김헌곤        삼성  0.302  117  311  281   43   85   8
14646  28750  2024         김헌곤        삼성  0.302  117  311  281   43   85   8
14647  10916  2024         김현수        LG  0.294  137  583  517   61  152  36
14648  28794  2024         김현수        LG  0.294  137  583  517   61  152  36
14649  10925  2024         김현종        LG  0.200   17   16   15    8    3   1
14650  28803  2024         김현종        LG  0.200   17   16   15    8    3   1
14651  10886  2024         김현준        삼성  0.224   79  205  183   23   41  10
14652  28764  2024         김현준        삼성  0.224   79  205  183   23   41  10
14653  11164  2024         김형준        NC  0.195  119  414  354   39   69  12
14654  29042  2024         김형준        NC  0.195  119  414  354   39   69  12
14655  11176  2024         김혜성        키움  0.326  127  567  509   90  166  26
14656  29054  2024         김혜성        키움  0.326  127  567  509   90  166  26
14657  10858  2024         김호령       KIA  0.136   64   67   59   12    8   2
14658  28736  2024         김호령       KIA  0.136   64   67   59   12    8   2
14659  10985  2024         김호준        두산  0.000    2    0    0    0    0   0
14660  10985  2024         김호준        두산  0.000    2    0    0    0    0   0
14661  28863  2024         김호준        두산  0.000    2    0    0    0    0   0
14662  28863  2024         김호준        두산  0.000    2    0    0    0    0   0
14663  10897  2024         김호진        삼성  0.069   26   32   29    4    2   0
14664  28775  2024         김호진        삼성  0.069   26   32   29    4    2   0
14665  11154  2024         김휘집        NC  0.258  140  562  488   78  126  24
14666  29032  2024         김휘집        NC  0.258  140  562  488   78  126  24
14667  10845  2024         나성범       KIA  0.291  102  424  374   51  109  17
14668  28723  2024         나성범       KIA  0.291  102  424  374   51  109  17
14669  11080  2024         나승엽        롯데  0.312  121  489  407   59  127  35
14670  28958  2024         나승엽        롯데  0.312  121  489  407   59  127  35

In [25]:
conn.close()